"""delete order draft status

Revision ID: 54daffd2c4ec
Revises: 496527da4175
Create Date: 2025-05-29 00:20:03.956419

"""
from typing import Sequence, Union
OrderDraftStatus = Union[str, Sequence[str]]
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54daffd2c4ec'
down_revision: Union[str, None] = '496527da4175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_draft') as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_draft') as batch_op:
        batch_op.add_column(sa.Column('status', validate_strings=True, default=OrderDraftStatus.COLLECTING))
    # ### end Alembic commands ###
