"""delete the product_name column

Revision ID: 5f6a68dac08b
Revises: 1b5464467918
Create Date: 2025-05-23 23:10:59.952637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6a68dac08b'
down_revision: Union[str, None] = '1b5464467918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order') as batch_op:
        batch_op.drop_column('product_name')
    with op.batch_alter_table('order_draft') as batch_op:
        batch_op.drop_column('product_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_draft') as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.TEXT(), nullable=True))
    with op.batch_alter_table('order') as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
