"""Fix shipment_method enum values to lowercase

Revision ID: 63bb1ccf4d1a
Revises: b6a4d45039f9
Create Date: 2025-05-15 16:01:35.998415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63bb1ccf4d1a'
down_revision: Union[str, None] = 'b6a4d45039f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
