"""刪掉 payload

Revision ID: d584f727dd73
Revises: 8f8738f7dfc1
Create Date: 2025-05-13 15:17:19.437092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd584f727dd73'
down_revision: Union[str, None] = '8f8738f7dfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'payload')
    op.drop_column('order_draft', 'payload_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_draft', sa.Column('payload_json', sa.TEXT(), nullable=False))
    op.add_column('notification', sa.Column('payload', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
