"""small modification

Revision ID: fec42806bf49
Revises: d584f727dd73
Create Date: 2025-05-13 21:15:12.488848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec42806bf49'
down_revision: Union[str, None] = 'd584f727dd73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_method', 'instructions',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_method', 'instructions',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
